version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080