export const BUSINESSES: readonly string[] = [
  'Office suites',
  'Social media',
  'Database',
  'Troubleshooting',
  'Data analysis',
  'Web analytics',
  'Javascript',
  'Python',
  'Django',
  'NodeJs',
  'Git',
  'Search Engine',
  'API',
  'Photoshop',
  'CMS',
  'Testing/Debugging',
  'Responsive Design',
  'SEO/SEM',
  'HTML & CSS',
  'WordPress',
  'Email marketing',
  'Web scraping',
  'CRO',
  'A/B Testing',
  'Search Engine',
  'Keyword Optimization',
  'B2B Marketing',
  'Brand management',
  'Creativity',
  'Sales',
  'CMS Tools',
  'Copywriting',
  'Storytelling',
  'Research',
  'Critical thinking',
  'Decision-making',
  'Attention to detail',
  'Teamwork',
  'Time management',
  'Communication',
  'Teamwork',
  'Stress management',
  'Problem-solving',
  'Productivity',
  'Organization',
  'Critical thinking',
  'Attention to detail',
  'Adaptability',
];

export const LANGUAGES: readonly string[] = [
  'English',
  'Chinese',
  'Spanish',
  'Portuguese',
  'Hindi',
  'Russian',
  'Korean',
  'French',
  'German',
  'Persian',
];
