export const BUSINESSES: readonly string[] = [
  'Back-End Developer',
  'Front-End Developer',
  'Full-Stack Developer',
  'SEO Engineer',
  'Product Manager',
  'Software Architect',
  'CONTENT MANAGER',
  'Data Analysts',
  'DevOps Architect',
  'DevOps Engineer',
  'Android Developer',
  'Web Developer',
  'Cloud engineer',
  'Game Developer',
  'UI Developer',
  'UX Developer',
];

export const LANGUAGES: readonly string[] = [
  'English',
  'Chinese',
  'Spanish',
  'Portuguese',
  'Hindi',
  'Russian',
  'Korean',
  'French',
  'German',
  'Persian',
];

export const SKILLS: readonly string[] = [
  'Office suites',
  'Social media',
  'Database',
  'Troubleshooting',
  'Data analysis',
  'Web analytics',
  'Javascript',
  'Python',
  'Django',
  'NodeJs',
  'Git',
  'Search Engine',
  'API',
  'Photoshop',
  'CMS',
  'Testing/Debugging',
  'Responsive Design',
  'SEO/SEM',
  'HTML & CSS',
  'WordPress',
  'Email marketing',
  'Web scraping',
  'CRO',
  'A/B Testing',
  'Search Engine',
  'Keyword Optimization',
  'B2B Marketing',
  'Brand management',
  'Creativity',
  'Sales',
  'CMS Tools',
  'Copywriting',
  'Storytelling',
  'Research',
  'Critical thinking',
  'Decision-making',
  'Attention to detail',
  'Teamwork',
  'Time management',
  'Communication',
  'Teamwork',
  'Stress management',
  'Problem-solving',
  'Productivity',
  'Organization',
  'Critical thinking',
  'Attention to detail',
  'Adaptability',
];
